version: "3"

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "5000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - webservices
      - front

  front:
    image: frontend
    stdin_open: true
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - /app/node_modules
    depends_on:
      - webservices

  webservices:
    build: .
    ports:
      - "3011:3011"
    environment:
      - PORT=3000
      - USER=test
      - PASSWORD=test
    volumes:
      - ./:/app
      - /app/node_modules
    depends_on:
      - mongo_app

  mongo_app:
    image: mongo:latest
    ports:
      - "27020:27017"
    volumes:
      - mongo-db:/data/db

volumes:
  mongo-db:
